version: '3.8'

services:
  backend:
    image: welshia1511/course-api-backend
    ports:
      - "8080:8080"

  frontend:
    image: welshia1511/course-api-frontend
    ports:
      - "3000:80"
